# Generated by Django 4.2.7 on 2023-11-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.db.models.deletion.SET_NULL, upload_to='post'),
        ),
    ]
